server:
  port: 8888

Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Students?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
    username: root
    password: root

    logging:
      path: /user/local/log
      level: debug
